name: kagura_sns
description: A new Flutter project.
publish_to: "none"

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cloud_firestore: ^4.5.3
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+3
  firebase_auth: ^4.4.2
  firebase_storage: ^11.1.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.19

  flutter_signin_button: ^2.0.0
  freezed_annotation: ^2.4.1
  google_sign_in: ^6.1.0
  image_picker: ^0.8.7+4
  json_annotation: ^4.8.1
  path_provider: ^2.0.14
  pedantic_mono: ^1.21.1
  pubspec_dependency_sorter: ^1.0.3
  the_apple_sign_in: ^1.1.1
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.2
flutter_icons:
  android: true
  ios: true
  image_path: "asstes/images/kagurasplash(1).png"
flutter_native_splash:
  ios_content_mode: center
  color: "#add8e6"
  image: "asstes/images/kagurasplash(1).png"
  color_dark: "#262626"
  image_dark: "asstes/images/kagurasplash(1).png"
  fullscreen: true

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

assets:
  - images/kagurasplash(1).png
